config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'feed',  to: 'static_pages#show'
  get    'signup',  to: 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'register',  to: 'menus#new'
  get    'menus/index',  to: 'menus#index'
  get    'lowcalorie',  to: 'menus#lowcalorie'
  get    'lowcarb',  to: 'menus#lowcarb'
  get    'lowsodium',  to: 'menus#lowsodium'
  get    'lowprice',  to: 'menus#lowprice'
  get    'glutenfree',  to: 'menus#glutenfree'
  get    'vege',  to: 'menus#vege'
  get    'like',  to: 'menus#like'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :feeds, only: [:show]
  resources :menus
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates :name , length: {  maximum: 30 } , presence: true
  validates :calorie , presence: true , numericality: {only_integer: true}
  mount_uploader :image, ImageUploader

  #お気に入りユーザーの設定
  has_many :liking_favorites, class_name:  "Favorite",
                              foreign_key: "user_id",
                              dependent:   :destroy
  has_many :liked_users, through: :liking_favorites, source: :user

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
    @menu = Menu.new
  end

  def index
    @menus = Menu.all.order("updated_at DESC").limit(50)
  end

  def create  
    @menu = Menu.new(menu_params)
    if @menu.save
      flash[:success] = "Enjoy Healthy Meal !"
      redirect_to @menu
    else
      render 'new'
    end
  end

  def show
    @menu = Menu.find(params[:id])
    @post = current_user.posts.build(@post_params)
  end
  
  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    @menu = Menu.find(params[:id])
    if @menu.update(menu_params)
      redirect_to edit_menu_path , notice: 'メニューを更新しました'
    else
      render 'edit'
    end
  end

  def lowcalorie
    @menus = Menu.order("calorie asc")
  end

  def lowcarb
    @menus = Menu.order("carb asc")
  end

  def glutenfree
    @glutenfrees = Menu.where(gluten: '0').order("updated_at DESC").limit(50)
  end

  def vege
    @veges = Menu.where(vege: '0').order("updated_at DESC").limit(50)
  end

  def like
    @likes = current_user.liking_menus.order("updated_at DESC").limit(50)
  end

  private
  def menu_params
    params.require(:menu).permit(:name, :calorie, :image, :protein, :lipid, :carb, :sodium, :price, :gluten, :vege, :type)
  end
end

app/views/menus/___action.html.erb
<div class="action">
  <% if current_user.liking? menu %>
    <%= render 'users/unlike' , menu: menu %>
  <% else %>
    <%= render 'users/like' , menu: menu %>
  <% end %> 

  <% unless current_page?(menu) %>
    <%= link_to "詳細" , menu , class: "btn btn-info btn-sm" %>
  <% end %>
</div>

app/views/menus/_action.html.erb
<div class="action">
  <% if current_user.like? menu %>
    <%= render 'menus/unlike' , menu: menu %>
  <% else %>
    <%= render 'menus/like' , menu: menu %>
  <% end %> 

  <% unless current_page?(menu) %>
    <%= link_to "詳細" , menu , class: "btn btn-info btn-sm" %>
  <% end %>
</div>

app/views/menus/_category.html.erb
    <div class="row">
      <div class="col-xs-6" style="background-color:#EA6052;"><%= link_to "低カロリー", lowcalorie_path %></div>
      <div class="col-xs-6" style="background-color:#7FB7FF;"><%= link_to "低糖質", lowcarb_path %></div>
    </div>
    <div class="row">
      <div class="col-xs-6" style="background-color:#FECC27;"><%= link_to "グルテンフリー", glutenfree_path %></div>
      <div class="col-xs-6" style="background-color:#17A980;"><%= link_to "ベジタリアン", vege_path %></div>
    </div><br>

app/views/menus/_menulist.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="container">
      <div class="container-inner inner-default clearfix">
        <% @menus.each do |menu| %>
          <div class="item-box">
            <div class="image">
              <div class="img-wrap">
              <p><%= render 'users/like_form' , menu: menu if logged_in? %></p>
              <p><%= image_tag menu.image.url, :width => '200' %></p>
              </div>
            </div>
            <div class="detail">
              <p class="title">
                <%= menu.name %> <%= menu.calorie %>[kcal]
              </p>
            </div>
          </div>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/menus/_signup.html.erb
<div class="row">
  <section class="col-xs-12">
    <div class="center jumbotron">
      <h1>Welcome to Mealthy</h1>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-danger" %>
    </div>
  </section>
</div>

app/views/menus/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <%= image_tag @menu.image.url, :width => '200' %>
    </div>
　  <section class="col-sm-6">
      <h3><%= @menu.name %></h3>
      <p>価格：<%= @menu.price %>円（税込）</p>
      <p>カロリー：<%= @menu.calorie %>kcal</p>
      <p>たんぱく質：<%= @menu.protein %>g</p>
      <p>脂質：<%= @menu.lipid %>g</p>
      <p>炭水化物：<%= @menu.carb %>g</p>
      <p>塩分（Na）：<%= @menu.sodium %>mg</p>
    </section><br>
  </div>
  
  <div class="row">
    <div class="col-xs-12">
      <%= form_for(@menu) do |f| %>

        <%= f.label :メニュー名 %>
        <%= f.text_field :name %>

        <%= f.label :カロリー（ｋｃａｌ） %>
        <%= f.text_field :calorie %>

        <%= f.label :たんぱく質（ｇ） %>
        <%= f.text_field :protein %>

        <%= f.label :脂質（ｇ） %>
        <%= f.text_field :lipid %>

        <%= f.label :炭水化物（ｇ） %>
        <%= f.text_field :carb %>

        <%= f.label :塩分（Ｎａ）（ｍｇ） %>
        <%= f.text_field :sodium %>

        <%= f.label :価格（円） %>
        <%= f.text_field :price %>

        <%= f.label :グルテン（０：なし、１：あり、２：不明） %>
        <%= f.text_field :gluten %>

        <%= f.label :ベジ（０：ベジ、１：ノンベジ、２：不明） %>
        <%= f.text_field :vege %>

        <%= f.label :メニュー写真 %>
        <%= f.file_field :image %><br><br>

        <%= f.submit  "S A V E  C H A N G E S", class: "btn btn-large btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/menus/glutenfree.html.erb
<% if logged_in? %>
  <%= render 'category' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="container-inner inner-default clearfix">
        <% @glutenfrees.each do |menu| %>
          <div class="item-box">
            <div class="image">
              <div class="img-wrap">
              <p><%= image_tag menu.image.url, :width => '200' %></p>
              </div>
            </div>
            <div class="detail">
              <p class="title">
                <%= menu.name %> <%= menu.calorie %>[kcal]
              </p>
            </div>
            <%= render 'users/like_form' , menu: menu if logged_in? %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>  
  
<% else %>
  <%= render 'signup' %>
<% end %>

app/views/menus/index.html.erb
<% if logged_in? %>
  <%= render 'category' %>
  <%= render 'menulist' %>

<% else %>
  <%= render 'signup' %>
<% end %>

app/views/menus/like.html.erb
<% if logged_in? %>
  <%= render 'category' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="container-inner inner-default clearfix">
        <% @likes.each do |menu| %>
          <div class="item-box">
            <div class="image">
              <div class="img-wrap">
              <p><%= image_tag menu.image.url, :width => '200' %></p>
              </div>
            </div>
            <div class="detail">
              <p class="title">
                <%= menu.name %> <%= menu.calorie %>[kcal]
              </p>
            </div>
            <%= render 'users/like_form' ,user: @user , menu: menu if logged_in? %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>  
  
<% else %>
  <%= render 'signup' %>
<% end %>

app/views/menus/lowcalorie.html.erb
<% if logged_in? %>
  <%= render 'category' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="container-inner inner-default clearfix">
        <% @menus.each do |menu| %>
          <div class="item-box">
            <div class="image">
              <div class="img-wrap">
              <p><%= image_tag menu.image.url, :width => '200' %></p>
              </div>
            </div>
            <div class="detail">
              <p class="title">
                <%= menu.name %> <%= menu.calorie %>[kcal]
              </p>
            </div>
            <%= render 'users/like_form' , menu: menu if logged_in? %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% else %>
  <%= render 'signup' %>
<% end %>

app/views/menus/lowcarb.html.erb
<% if logged_in? %>
  <%= render 'category' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="container-inner inner-default clearfix">
        <% @menus.each do |menu| %>
          <div class="item-box">
            <div class="image">
              <div class="img-wrap">
              <p><%= image_tag menu.image.url, :width => '200' %></p>
              </div>
            </div>
            <div class="detail">
              <p class="title">
                <%= menu.name %> <%= menu.calorie %>[kcal]  (<%= menu.carb %>[g])
              </p>
            </div>
            <%= render 'users/like_form' , menu: menu if logged_in? %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% else %>
  <%= render 'signup' %>
<% end %>

app/views/menus/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <%= form_for(@menu) do |f| %>

        <%= f.label :メニュー名 %>
        <%= f.text_field :name %>

        <%= f.label :カロリー（ｋａｃｌ） %>
        <%= f.text_field :calorie %>

        <%= f.label :たんぱく質（ｇ） %>
        <%= f.text_field :protein %>

        <%= f.label :脂質（ｇ） %>
        <%= f.text_field :lipid %>

        <%= f.label :炭水化物（ｇ） %>
        <%= f.text_field :carb %>

        <%= f.label :塩分（Ｎａ）（ｍｇ） %>
        <%= f.text_field :sodium %>

        <%= f.label :価格（円） %>
        <%= f.text_field :price %>

        <%= f.label :グルテン（０：なし、１：あり、２：不明） %>
        <%= f.text_field :gluten %>

        <%= f.label :ベジ（０：ベジ、１：ノンベジ、２：不明） %>
        <%= f.text_field :vege %>

        <%= f.label :メニュー写真 %>
        <%= f.file_field :image %><br><br>

        <%= f.submit "R E G I S T E R", class: "btn btn-large btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/menus/show.html.erb
<% content_for :head do %>
  <title>
    <%= @menu.name %> - Mealthy
  </title>
  <meta name="description" content="<%= @menu.name %>に関する情報です">
  <meta name="keywords" content="Mealthy,<%= @menu.name %>">
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <%= image_tag @menu.image.url, :width => '200' %>
      
      <div id="like_form">
        <br>
        <% if current_user.like?(@menu) %>
          <%= render 'users/unlike' , menu: @menu %>
        <% else %>
          <%= render 'users/like' , menu: @menu %>
        <% end %>
      </div>
    </div>
　  <section class="col-sm-6">
      <h3><%= @menu.name %></h3>
      <p>価格：<%= @menu.price %>円（税込）</p>
      <p>カロリー：<%= @menu.calorie %>kcal</p>
      <p>たんぱく質：<%= @menu.protein %>g</p>
      <p>脂質：<%= @menu.lipid %>g</p>
      <p>炭水化物：<%= @menu.carb %>g</p>        
      <p>塩分（Na）：<%= @menu.sodium %>mg</p>
    </section><br>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/post_form' %>
    </div>
  </div>
</div>

app/views/menus/vege.html.erb
<% if logged_in? %>
  <%= render 'category' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="container-inner inner-default clearfix">
        <% @veges.each do |menu| %>
          <div class="item-box">
            <div class="image">
              <div class="img-wrap">
              <p><%= image_tag menu.image.url, :width => '200' %></p>
              </div>
            </div>
            <div class="detail">
              <p class="title">
                <%= menu.name %> <%= menu.calorie %>[kcal]
              </p>
            </div>
            <%= render 'users/like_form' , menu: menu if logged_in? %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>  
  
<% else %>
  <%= render 'signup' %>
<% end %>