config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'feed',  to: 'static_pages#show'
  get    'signup',  to: 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'register',  to: 'menus#new'
  get    'menus/index',  to: 'menus#index'
  get    'lowcalorie',  to: 'menus#lowcalorie'
  get    'lowcarb',  to: 'menus#lowcarb'
  get    'lowsodium',  to: 'menus#lowsodium'
  get    'lowprice',  to: 'menus#lowprice'
  get    'glutenfree',  to: 'menus#glutenfree'
  get    'vege',  to: 'menus#vege'
  get    'like',  to: 'menus#like'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :feeds, only: [:show]
  resources :menus
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <nav>
    <ul>
      <li><%= link_to "Register", register_path %></li>
      <li><%= link_to "Search", menus_path %></li>
      <li><%= link_to "Live", posts_path %></li>
      <% if logged_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <span class="gravatar">
            <%= image_tag current_user.image.url, :size => '25x25' %>
          </span>
          <span class="caret"></span>
        </a>
            <ul class="dropdown-menu">
              <li><%= link_to "フィード", current_user %></li>
              <li class="divider"></li>
              <li><%= link_to "お気に入り", like_path %></li>
              <li class="divider"></li>
              <li><%= link_to "アカウント設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "友達を招待", "#" %></li>
              <li class="divider"></li>
              <li><%= link_to "お問い合わせ", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
        </li>
      <% else %>
        <li><%= link_to "ログイン", login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

<div class="logo">
  <%= link_to image_tag('logo-color.png'), root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Mealthy Spin off</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <%= render 'layouts/header' %><br>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
    
</body>
</html>